### ISSUE TITLE
Tree not displayed correctly in Chrome

### ISSUE THREAD

**Issue by benediktrauscher** [emepyc/tnt.tree#5]
Hello Miguel,

today I noticed that trees are not rendered correctly anymore on Google Chrome version 50.0.2661.86 (64-bit):

![screen shot 2016-04-25 at 16 50 45](https://cloud.githubusercontent.com/assets/9319339/14787921/e5a2e332-0b05-11e6-82e1-9b12c9f734b4.png)

Any idea what might be causing this? I don't see any Exception/Error in the console.

Many thanks

Benedikt

**Comment by emepyc** [comment]
Hi Benedikt,
Yes, I have noticed that today as well. It looks like a bug in Chrome v50. Prev version works fine. Safari and Firefox still displays the tree correctly. I'll open an issue and try to work on a fix

**Comment by emepyc** [comment]
I have pushed a change to github (master branch), can you check it is working for you? If so, I'll publish a new version

**Comment by emepyc** [comment]
This is now fixed in version 0.1.3

**Comment by benediktrauscher** [comment]
Hi Miguel,

works perfectly, thank you very much!
