### ISSUE TITLE
Is it possible to re-root the tree?

### ISSUE THREAD

**Issue by aziele** [emepyc/tnt.tree#6]
Hello, 

I'm trying to re-root the tree using the following snippet of code:

```
tree_vis.root();
var node = root.find_node_by_name("node_name");
tree_vis.root(node);
```

But it doesn't do anything.

**Comment by emepyc** [comment]
Hi,
The API doesn't offer a way to reroot the tree in one step. To do that you need to create a new tree based on the node you want to focus on. This should do the trick:

``` javascript
// reroot on node 'x'
var root = tree_vis.root();
var node = root.find_node_by_name('x');
var xTree = root.subtree(node.get_all_leaves());

tree_vis.data(xTree.data());
tree_vis.update();

// To show the full tree again:
tree_vis.data(root.data());
tree_vis.update();
```

I will think about an easier way to do this, in the meantime I will update the documentation to avoid confusion.

**Comment by aziele** [comment]
Thank you for your quick response, Miguel. I tried your code, but unfortunately I couldn't make it work. Most likely, I'm doing something wrong. 

I created a sample HTML file with my code (attachment). I would greatly appreciate if you could look at this. The TnT Tree library is a great tool in my work - everything works like a charm. The only functionality that I'm missing and trying to implement without success is capability to re-root the existing tree when clicking at certain branch.

[test.html.txt](https://github.com/tntvis/tnt.tree/files/248906/test.html.txt)

**Comment by emepyc** [comment]
In the snippet I posted above, the two lines of code at the end are for showing the full tree again, you shouldn't call them immediately after rerooting (you are re-rooting and immediately after that showing always the full tree again!).

Take a look at your fixed code here:
http://bl.ocks.org/emepyc/f26a835ffc6ccd1a45bd4b2f66e794e4

**Comment by aziele** [comment]
Thank you very much for all your help! Now, everything is clear to me. 

It's funny, because apparently we think different about rooting the tree. I'm thinking about selecting a node that will be an outgroup for other nodes. Hence, the root stems from the base of the tree. 

![outgrouprooting](https://cloud.githubusercontent.com/assets/1017422/15045716/6784a222-12dc-11e6-8bed-d3655655451d.png)

So I'm guessing this option is not implemented in your Tnt Tree library. I will then do the re-rooting of Newick format on the server-side and return the converted tree back to the TnT Tree.

**Comment by emepyc** [comment]
Ah, ok. No, we have the same idea of what rerooting a tree is. I just got confused about the snippet you wrote in the first place. Sorry for making this short story that long :-)
The library doesn't reroot trees. Doing that server side sounds like a good approach
