### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by piotr-gawron** [emepyc/tnt.tree#8]
The code in "# Example" section of your documentation is a bit broken. There are problems with brackets. Here is as it shoudl look (normally I would provide wit PR, but I coudln't find source of your documentation):

```
// Input tree
var newick = '((human, chimp),mouse)';
var treeObj = tnt.tree.parse_newick(newick);

// Tree visualisation configuration
var tree = tnt.tree()
    .data(treeObj)
    .layout (tnt.tree.layout.vertical()
  	      .width(650)
    )
    .node_display (tnt.tree.node_display.circle()
        .size(5)
  	.fill(function (node) {
            if (node.is_leaf()) { // THERE WAS MISSING BRACKET ')' HERE
                return "blue";
            } //THERE WAS extra BRACKET ')' HERE 
            return "green";
        })) // THERE WAS MISSING BRACKET ')' HERE
	    
    .label (tnt.tree.label.text()
        .height(30)
        .text (function (node) {
            return node.property("name");
        })
    );
	
// Tree rendering
tree (document.getElementById("divId"));
```

Second issue that I found is that the code above produce slightly strange tree (everything is in one vertical line). I think there is an issue with scaling. Adding `.scale(false)` after `.width(650)` fix the issue.

**Comment by emepyc** [comment]
Thanks, I'll take a look.
The documentation is in the gh-pages if you prefer to make a PR:
https://github.com/tntvis/tnt.tree/blob/gh-pages/index.html#L51

**Comment by emepyc** [comment]
It's fixed now.
Regarding the "strange tree", by default the tree is displayed using the branch lengths provided in the input tree. Since the example tree doesn't have them set all branches had length 0. As you have guessed, the fix is to add the <code>.scale(false)</code> option to the layout.
Thanks again for the heads up.
