### ISSUE TITLE
npm install -> node_modules/tnt.tree/build/ is missing in 0.1.10

### ISSUE THREAD

**Issue by guidorice** [emepyc/tnt.tree#9]
Hi, I had to revert to 0.1.9 to be able to build my javascript project. When 0.1.10 is installed by npm, it looks like the build/ directory is missing.

**Comment by emepyc** [comment]
Yes, this has been done on purpose.
The `build` directory can be created using:

```
npm install
gulp build-browser
// minified
gulp build-browser-min
```

If you just want the latest version you can take it from the documentation:
http://tntvis.github.io/tnt.tree/build/tnt.tree.js
http://tntvis.github.io/tnt.tree/build/tnt.tree.min.js
http://tntvis.github.io/tnt.tree/build/tnt.tree.css

Do you think this may cause any inconvenience?
The main problem could be when I release a new backwards-incompatible version, but in that case I can serve both links from the documentation?

**Comment by emepyc** [comment]
Ah, ok. Yes, you are right, my intention was to leave the `build` directory out of the repo (github), but it should be included in the npm package.
I have now bumped a new version that includes the compiled lib (0.1.11)

**Comment by guidorice** [comment]
Hi I just now installed 0.1.11 but I am experiencing the same problem with the npm installation.

So I am no expert on npm publishing, but I can share my experience with you as a consumer of npm modules. It is preferred if you can distribute the build files with the npm install. Because it removes one manual step from my javascript  build process. 

I am using tnt.tree in a aurelia-cli (http://aurelia.io/) project with a lot of other dependencies.  Aurelia uses gulp under the hood to perform it's builds. For some reason the only way I have been able to use tnt.tree in this build is by  targeting the file `build/tnt.tree.js` by adding this to my aurelia.json config in a`dependencies` section:
```
{
  "name" : "tnt.tree",
  "path" : "../node_modules/tnt.tree/build/tnt.tree"
},
```

Here are some notes from aurelia about how 3rd party libraries can be included and different variations about how npm packages might be structured. I tried various ways of pulling tnt.tree into the build, but the above method is the only way it would work.

http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/the-aurelia-cli/6

**Comment by emepyc** [comment]
Yay.
I forgot that if there is no `.npmignore` npm takes `.gitignore` for publishing.
There is a new version `0.1.12` that should include the `build` folder again.

Regarding building with `aurelia` I haven't used it so I can't comment much on that, but if you open a new issue I can try to take a look and see if I can figure out how to build them together

**Comment by guidorice** [comment]
Hey Miguel, the 0.1.12 build looks good. This is a fine solution for now. I will let you know if I come up with any other suggestions about how the npm module could be differently packaged. That is beyond my expertise at this time. Thanks so much!
